import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import { cn } from "@/lib/utils";
import { UserAuthForm } from "@/components/form";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";

export const metadata: Metadata = {
  title: "Cursilho de Cristandade - Igreja Cristã em Recife",
  description: "Generated by create next app",
};

export default function AuthenticationPage() {
  return (
    <>
      <div className="container relative hidden h-screen flex-col items-center justify-center md:grid lg:max-w-none lg:grid-cols-2 lg:px-0">
        <Link href="/examples/authentication" className={cn(buttonVariants({ variant: "ghost" }), "absolute right-4 top-4 md:right-8 md:top-8")}>
          Login
        </Link>
        <div className="relative hidden h-full flex-col bg-muted p-10 text-white dark:border-r lg:flex">
          <div className="absolute inset-0 bg-zinc-900 " />
          <div className="relative z-20 flex items-center text-lg font-medium">
            <Image src="/logo.png" width={50} height={50} alt="Logo" className="mr-2" />
            Igreja Cristã em Recife
          </div>
          <div className="relative z-20 mt-auto">
            <Card className="p-4 text-left">
              <CardHeader>
                <h1 className="text-2xl font-semibold tracking-tight">Cursilho Masculino</h1>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground">Data: 10/11/2023</p>
                <p className="text-sm text-muted-foreground">Local: por ai po</p>
              </CardContent>
            </Card>
          </div>
          <div className="relative z-20 mt-auto">
            <blockquote className="space-y-2">
              <p className="text-lg">&ldquo;O Cursilho de Cristandade é uma jornada transformadora que ilumina corações, fortalece a fé e inspira ações cristãs, guiando cada passo rumo a uma vida plena no amor de Deus.&rdquo;</p>
              <footer className="text-sm">Pr. Bruno Moraes</footer>
            </blockquote>
          </div>
        </div>
        <div className="lg:p-8">
          <div className="mx-auto flex w-full flex-col justify-center space-y-6">
            <div className="flex flex-col space-y-2 text-center w-full">
              <h1 className="text-2xl font-semibold tracking-tight">Ficha de inscrição</h1>
              <Card className="p-4 text-left">
                <p className="text-sm text-muted-foreground font-bold">O Cursilho destina-se a pessoas capazes de:</p>
                <p className="text-sm text-muted-foreground">● Capter a mensagem CRISTÃ e compreender o sentido da vida</p>
                <p className="text-sm text-muted-foreground">● Descobrir seus dons e talentos e por em pratica a serviço da comunidade</p>
                <p className="text-sm text-muted-foreground">● Ser fermento do EVANGELHO em seus ambientes e seu lar</p>
              </Card>
            </div>
            <UserAuthForm />
          </div>
        </div>
      </div>
    </>
  );
}
